import type { Metadata } from "next";
import "./globals.css";
import { Header } from "@/components/header";
import { Footer } from "@/components/footer";

import NavigationProgressBar from "@/components/navigation-progressbar-provider";
import { cn } from "@/util/cn";
import { roboto } from "@/util/font";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="tr">
      <body
        className={cn("flex min-h-screen min-w-96 flex-col", roboto.className)}
      >
        <NavigationProgressBar>
          <Header />
          <div className="flex flex-1 flex-col">{children}</div>
          <Footer />
        </NavigationProgressBar>
      </body>
    </html>
  );
}
