import type { Metadata } from "next";
import "./globals.css";
import { getVersions } from "@/service/get-versions";
import { Header } from "@/components/header";
import { Footer } from "@/components/footer";
import { getActiveVersion } from "@/service/get-active-version";

import NavigationProgressBar from "@/components/navigation-progressbar-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const versions = await getVersions();
  const activeVersion = await getActiveVersion();
  return (
    <html lang="tr">
      <body className="flex min-h-screen min-w-96 flex-col">
        <NavigationProgressBar>
          <Header versions={versions} activeVersion={activeVersion} />
          <div className="flex-1">{children}</div>
          <Footer />
        </NavigationProgressBar>
      </body>
    </html>
  );
}
